### ISSUE TITLE
error

### ISSUE THREAD

**Issue by codingaslu** [kaymen99/langgraph-email-automation#1]
langgraph.errors.InvalidUpdateError: Must write to at least one of ['emails', 'viewed_emails_ids', 'ready_emails', 'email_sender', 'email_category', 'email_subject', 'generated_email', 'rag_questions', 'retrieved_infos', 'review', 'trials']

**Comment by kaymen99** [comment]
The code run without error on my side, i don't know where the error is coming from yet (could be a langgraph update) but I have a quick fix for it (following the discussion [here](https://github.com/langchain-ai/langgraph/issues/740)), you should initialize any state variable when calling the app, update `main.py` with this:  

```python
print(Fore.GREEN + "Starting workflow..." + Style.RESET_ALL)
for output in app.stream({"trials": 0}):
    for key, value in output.items():
        pprint(Fore.CYAN + f"Finished running: {key}:" + Style.RESET_ALL)
```

It should work fine for now, I will try to understand where the issue is coming from.
